Add checksum property to tar_package
chef-cookbooks/tar pull request #50
Opened 2017-10-03 20:48 UTC by eheydrick

### Description

Add `checksum` property to `tar_package` resource. Also make the properties in the README look better. 

### Issues Resolved

#44 

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

2017-10-16 21:56 UTC, iennae commented on resources/package.rb
> +    checksum r.checksum
Can you add a conditional here? Otherwise it will break for folks that don't provide a checksum.

2017-10-16 22:30 UTC, iennae requested changes

2017-10-16 22:30 UTC, iennae commented on resources/package.rb
> +    checksum r.checksum
Realizing this doesn't need this, and instead we should not add a test for checksum to the test recipe.

2017-10-16 22:30 UTC, iennae commented on test/cookbooks/test/recipes/default.rb
> +  checksum '23ffc2de52d687739fed6dc2fc94df36aa7da7bb52c8740c523fdd7336fdbc8c'
As this is just exercising the underlying remote_file resource that is used this isn't needed. It's just adding extra work if the package name is updated.

2017-10-16 22:30 UTC, iennae commented on test/cookbooks/test/recipes/default.rb
> +  checksum '23ffc2de52d687739fed6dc2fc94df36aa7da7bb52c8740c523fdd7336fdbc8c'
As this is just exercising the underlying remote_file resource that is used this isn't needed. It's just adding extra work if the package name is updated.

2018-07-24 21:58 UTC, eheydrick commented
Made requested changed, rebased, and ready to merge.

2025-07-28 15:46 UTC, cgunasree08 commented
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).

2025-07-28 15:46 UTC, closed without merging